version: '3.7'
services:
    app:
        container_name: dockerized-reactjs-app
        build:
            context: .
            dockerfile: docker/Dockerfile.development
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development